#
GET http://localhost:3000/api/eletro/eletros/1

###
#
POST http://localhost:3000/api/eletro
Content-Type: application/json
{
    "nome":"ventilador",
    "kwh":56,
    "userId":1
}
###

#
GET http://localhost:3000/api/eletro/:id

###

#
PUT http://localhost:3000/api/eletro/:id
Content-Type: application/json
{
    "nome":"ventilador",
    "kwh":10,
    "userId":1
}
###

#
DELETE http://localhost:3000/api/eletro/:id
###

#
DELETE http://localhost:3000/api/eletro/

###